### ISSUE TITLE
Zugnummeränderung: Nachfolgezug zeichnen

### ISSUE THREAD

**Issue by manuel3108** [manuel3108/Gleisbelegung#10]
Wenn ein Zug seine Nummer ändert (E-Flag) sollte der Zug sofort mit der neuen Zugnummer gezeichnet werden, und nicht erst am nächsten Halt

**Comment by Stellwerksim123** [comment]
ich kümmere mioch drum
lokal funktioniert die Anzeige der nächsten Zugnummer schon (war ja schon fast alles vorbereitet)
werde jetzt noch die richtige Anzeige der zeit in der Suchleiste implementieren (bis jetzt ist überall die Abfahrtszeit am letzten Halt des ersten Zuges 01:00 und die ANkunftszeit des zweiten zuges am Start 01:00) ich denke ich werde das jeweils so ändern das bei beiden Zügen ankunft und abfahrt am wechselhalt gleich sind

**Comment by manuel3108** [comment]
Das klingt gut. Wie kommst du so mit dem Code zurecht?

**Comment by manuel3108** [comment]
@Stellwerksim123 Kommst du voran? Brauchst du Hilfe? Wie ist dein Fortschritt?

**Comment by Stellwerksim123** [comment]
@manuel3108 komme eigentlich ganz gut zurecht, 
da ich in den letzten Tagen nicht mehr so häufig zum coden kam und zwischenzeitlich auch noch ein (behobener) Fehler auftrat ist mein Stand immer noch gleich
assignen kann ich meines Wissens nicht
@Greonyral da du ja nun dich um da Problem kümmerst wird ich mal meinen aktuellen Stand hochladen, Stand ist wie oben beschrieben

**Comment by manuel3108** [comment]
@Stellwerksim123 Uuupppss, da habe ich den falschen assigned. Das muss ich mal schnell ändern. Das war keine Absicht.
Alles klar, hat mich nur gewundert. Lass dir ruhig Zeit. 

Nur zu deiner Info: plane ich Momentan am 29.03.2018 zu veröffentlichen. Ist das für dich denkbar, deinen Teil bis dahin fertig zu bringen, oder eher nicht?

**Comment by Stellwerksim123** [comment]
ok, denke das bekomme ich hin.
kurze Frage: wenn man in der Zugsuche nach einem Zug sucht, der an einem Halt wechselt, wird am Wechselhalt nur der alte Zug gefunden.
Beispiel: Zug 1 hält Bahnsteig X und Y an Y wird auf Zug 2 gewechselt, Zug 2 hält außerdem an Bahnsteig Z
Gibt man nun Zug 1 ein, blinken X und Y; gibt man Zug 2 ein, blinkt nur Z
Soll das so beibehalten werden oder soll der Wechselhalt z.B. bei beiden Zügen blinken (d.h. Y blinkt bei Zug 1 und 2 um im Beispiel zu bleiben)?

**Comment by manuel3108** [comment]
Der Wechselhalt darf sehr gerne auch bei beiden Zügen blinken. Macht irgendwie auch Sinn, war mir so aber noch nicht aufgefallen.
