### ISSUE TITLE
Problems with Exceptions when all Windows are closed

### ISSUE THREAD

**Issue by manuel3108** [manuel3108/Gleisbelegung#17]
I am currently working on #15.
When the Plugin throws an error, between the user pressed connect and the display of the main-window, the Plugin throws that error but does not terminate its process.

This may also occurs in other situations.

**Comment by Greonyral** [comment]
You would like to set the default exception handler before the user is allowd to press the `Connect` button. https://docs.oracle.com/javase/8/docs/api/java/lang/Thread.html#setUncaughtExceptionHandler-java.lang.Thread.UncaughtExceptionHandler- The method is not static and therefore must be called for the instance of the thread throwing the exception. As a workaround: Wrap the methods into `try-catch` blocks and delegate the exception handling explicitly.
