### ISSUE TITLE
Connection to STS Official Plugin Tester sometimes breaks during initialization

### ISSUE THREAD

**Issue by manuel3108** [manuel3108/Gleisbelegung#2]
Happens on current master (0fb0f28d672329ec843c6cde3b5dc45ea189918a) and other branches.

Plugin exits with message "Closing socket" in `System.err`

**Comment by Greonyral** [comment]
I tried to verify the issue but had no success. Did you try to connect by the IP or a domain name (and this maybe issues with DNS system)?

**Comment by manuel3108** [comment]
Yes, I tried by IP (127.0.0.1). I will have a look if it happens again

**Comment by Greonyral** [comment]
I finally could reproduce the error once. 
```
java.io.IOException: The markup in the document following the root element must be well-formed.
	at js.java.tools.xml.xmlreader.updateDataByString(xmlreader.java:291)
	at js.java.isolate.sim.sim.plugin.ServImpl.run(ServImpl.java:261)
	at java.lang.Thread.run(Thread.java:748)
``` 
has been logged to the PluginTester. That error is reproducible if you start the plugin, then the tester and then press the connect button. After dumping the XML to a file, the error did not occur. 
For me it looks like a bug of PluginTester to accept connections while not being entirely ready to process the XML. 

Long story short: Not a bug of our application.
