### ISSUE TITLE
Verbesserung der BahnhofsLabel

### ISSUE THREAD

**Issue by manuel3108** [manuel3108/Gleisbelegung#67]
- Links-Klick auf BahnhofsLabel soll alle Bahnsteige des Bahnhofes hervorheben
- Rechts-Klick auf BahnhofsLabel soll Einstellungen ähnlich wie bei den Bahnsteigen aufrufen
   - Alle betroffenen Bahnsteige ausblenden
   - Verschieben von gesamten Bahnhöfen
   - Ein und Ausblenden von gesamten Bahnhöfen

**Comment by DeeJayBro** [comment]
Wenn man gesamte Bahnhöfe verschieben kann, soll das verschieben von Bahngleisen dann nur noch im Bahnhof funktionieren?

**Comment by manuel3108** [comment]
Nein, es soll auch nach außerhalb eines Bahnhofes verschoben werden können. Ich habe mir schon viel Mühe gegeben, dass das möglich sein wird, und es wird nicht mehr so lange dauern, bis es fertig ist.
