### ISSUE TITLE
Alternativtext für Bahnhöfe

### ISSUE THREAD

**Issue by manuel3108** [manuel3108/Gleisbelegung#69]
EDIT; @DeeJayBro bearbeitet diesen Issue.

Da einige Bahnhöfe auch manchmal keinen Namen haben können, ist es sinnvoll einen alternativtext festlegen zu können.
Dies sollte im Einstellungsfenster des jeweiligen Bahnhofes möglich sein.

**Comment by DeeJayBro** [comment]
würde ich machen

**Comment by manuel3108** [comment]
Das klingt gut. Ich habe mir folgendes vorgestellt: Angenommen ein Bahnhof heißt FF, dann wäre meine Überlegung gewesen, so etwas entstehen zu lassen: BenutzerBahnhofsName(FF). Bin aber für andere Ideen offen.

Weiß zufällig jemand von euch, wie man aussenstehende (heißt read-only) User zu einem Issue assignen kann. Also hier würde ich gerne @DeeJayBro assignen, allerdings lässt mich Github das nicht tun. Ein kurzes Googlen lieferte mir auch keine Ergebnisse

**Comment by cmfcmf** [comment]
> Weiß zufällig jemand von euch, wie man aussenstehende (heißt read-only) User zu einem Issue assignen kann. Also hier würde ich gerne @DeeJayBro assignen, allerdings lässt mich Github das nicht tun. Ein kurzes Googlen lieferte mir auch keine Ergebnisse

Ja, das geht leider nicht :( Nur Leute mit Collaborator=write Status kann man assignen.

**Comment by manuel3108** [comment]
Ok, danke. Dann muss ich das wohl so wie oben immer manuell dazuschreiben. Danke für die Info
