### ISSUE TITLE
Überarbeitung der Verbindngs-Klasse

### ISSUE THREAD

**Issue by manuel3108** [manuel3108/Gleisbelegung#79]
Insbesonder soll hier die `update`-Methode erwähnt werden, die im gleichen Zug auch in mehrere Methoden ausgelagert werden könnte. 

Es ist außerdem eine genauere Analyse der Rückgabewerte der Schnittstelle notwendig, da es nicht sein kann, dass so häufig wie in einigen Logs die Daten eines Zuges nicht vollständig gesetzt werden.

Genauere Infos zur Schnittstelle gibts im  [STS-Handbuch](https://doku.stellwerksim.de/doku.php?id=stellwerksim:plugins:spezifikation)

**Comment by Greonyral** [comment]
Problem scheint mittlerweile behoben zu sein, ich habe den Fehler seit #81(Teil von 1.5) nicht mehr in den Log-Files.

**Comment by manuel3108** [comment]
Das ist gut, dann mache ich hier voresrst einmal zu. Ich habe nämlich momentan keine Lust diese Klasse neu zu schreiben, vorallem wenn ja alles funktioniert
