### ISSUE TITLE
Manifest korrigieren und aufräumen

### ISSUE THREAD

**Issue by DevonFrosch** [manuel3108/Gleisbelegung#82]
Hallo,

im Moment gibt es 2 Manifest-Dateien:
/src/META-INF/MANIFEST.MF
/out/production/Plugin Gleisbelegung/META-INF/MANIFEST.MF

Mit den letzten Änderungen wurden Dateien umbenannt, aber nur die 2. Manifest korrigiert - das veröffentlichte JAR wurde aber anscheinend mit dem 1. Manifest gebaut. Vielleicht wäre es sinnvoll, eine der Manifest-Dateien zu löschen.

**Comment by manuel3108** [comment]
Behoben mit f9a6d58. Danke für den Fix.
