### ISSUE TITLE
Fenster.java:589: ConcurrentModificationException

### ISSUE THREAD

**Issue by manuel3108** [manuel3108/Gleisbelegung#93]
```
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.util.ArrayList$Itr.next(Unknown Source)
	at com.gleisbelegung.Fenster.update(Fenster.java:589)
	at com.gleisbelegung.Plugin.lambda$run$25(Plugin.java:520)
```
[http://manuel-serret.bplaced.de/Gleisbelegung/fehler.php?id=286](url)

**Comment by Greonyral** [comment]
Fenster Zeile 589 ist bei aktueller Version eine Leerzeile, https://github.com/manuel3108/Gleisbelegung/blob/fd2e1cf5da3184d9ecde71b8d41325b78937d1fb/Plugin%20Gleisbelegung/src/com/gleisbelegung/Fenster.java. 

Generelle Ursache des Problems: Iteration `(for element in liste)` über Liste, die innerhalb (Fehler tritt sehr regelmäßig auf, eigener Thread modifiziert Liste) bzw während (anderer Thread modifiziert Liste, paralle Ausführung,Fehler tritt nur sporadisch auf) der Iteration verändert wird.
Im ersten Fall hilft Änderungen der Liste ausserhalb der Iteration durchzuführen. Im letzteren Fall nur die Nebenläufigkeit mit `synchronized(liste) { .. }` Blöcken zu unterbinden.

Da ich den Fehler auch nach längerer Nutzung des Plugins reproduzieren kann, vermute ich den parallelen Fall. @manuel3108 weisst du welche Liste an einer Code-Stelle modifiziert wird und innerhalb der Fenster Klasse den Fehler verursachen könnte?

**Comment by manuel3108** [comment]
Cool, dass du noch da bist.
Ich glaube ich habe vor der letzten Veröffentlichung vergessen, die Version anzupassen. Du hast natürlich völlig recht, in 1.6 kann der Fehler nicht dort liegen. Ich habe mir deshalb gerade mal die 1.5er-Branch angeschaut und ich denken, dass der Fehler dort logisch ist.
[https://github.com/manuel3108/Gleisbelegung/blob/1.5/Plugin%20Gleisbelegung/src/com/gleisbelegung/Fenster.java#L589](url)

Es scheint sich hierbei um die Zugliste zu handeln, was auch meine Befürchtung war. Ich schätze, dass es relativ schwierig/Aufwändig wird den Fehler vollständig herauszubekommen.

**Comment by Greonyral** [comment]
Wenn deine Vermutung stimmt, sollte der Pull-Request #96 das Problem beheben.

**Comment by manuel3108** [comment]
Werde ich mir später mal genauer anschauen...
